-- MASTER FIX SCRIPT
-- This script fixes ALL potential issues:
-- 1. Creates missing tables (profiles, applications, subscriptions)
-- 2. Sets up Triggers (so NEW users are automatically added)
-- 3. Sets up RLS Permissions (so Admin 'nbamoment' can see everything)
-- 4. Syncs EXISTING users (so old accounts appear in the list)

-- Part 1: Ensure Tables Exist
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  email TEXT UNIQUE,
  role TEXT DEFAULT 'standard' CHECK (role IN ('standard', 'advanced', 'admin')),
  trading_account TEXT,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.premium_applications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE,
  email TEXT,
  trading_account TEXT NOT NULL,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.subscriptions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE,
  strategy_id TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(user_id, strategy_id)
);

-- Part 2: Enable RLS and Admin Policies
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.premium_applications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.subscriptions ENABLE ROW LEVEL SECURITY;

-- Remove old policies to avoid conflicts
DROP POLICY IF EXISTS "Super Admin Manage Profiles" ON public.profiles;
DROP POLICY IF EXISTS "Super Admin Manage Applications" ON public.premium_applications;
DROP POLICY IF EXISTS "Super Admin Manage Subscriptions" ON public.subscriptions;

-- Create Super Admin Policies (Email OR UUID)
CREATE POLICY "Super Admin Manage Profiles" ON public.profiles FOR ALL
USING (
  (auth.jwt() ->> 'email') = 'nbamoment@gmail.com' OR
  auth.uid() = 'c337aaf8-b161-4d96-a6f4-35597dbdc4dd'
)
WITH CHECK (
  (auth.jwt() ->> 'email') = 'nbamoment@gmail.com' OR
  auth.uid() = 'c337aaf8-b161-4d96-a6f4-35597dbdc4dd'
);

CREATE POLICY "Super Admin Manage Applications" ON public.premium_applications FOR ALL
USING (
  (auth.jwt() ->> 'email') = 'nbamoment@gmail.com' OR
  auth.uid() = 'c337aaf8-b161-4d96-a6f4-35597dbdc4dd'
)
WITH CHECK (
  (auth.jwt() ->> 'email') = 'nbamoment@gmail.com' OR
  auth.uid() = 'c337aaf8-b161-4d96-a6f4-35597dbdc4dd'
);

CREATE POLICY "Super Admin Manage Subscriptions" ON public.subscriptions FOR ALL
USING (
  (auth.jwt() ->> 'email') = 'nbamoment@gmail.com' OR
  auth.uid() = 'c337aaf8-b161-4d96-a6f4-35597dbdc4dd'
)
WITH CHECK (
  (auth.jwt() ->> 'email') = 'nbamoment@gmail.com' OR
  auth.uid() = 'c337aaf8-b161-4d96-a6f4-35597dbdc4dd'
);

-- Part 3: Setup Trigger for NEW Users
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, email, role)
  VALUES (new.id, new.email, 
    CASE WHEN new.email = 'nbamoment@gmail.com' THEN 'admin' ELSE 'standard' END
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Re-create trigger safely
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- Part 4: SYNC EXISTING USERS (Crucial for Empty List)
INSERT INTO public.profiles (id, email, role)
SELECT 
    id, 
    email, 
    CASE WHEN email = 'nbamoment@gmail.com' THEN 'admin' ELSE 'standard' END
FROM auth.users
ON CONFLICT (id) DO UPDATE 
SET email = EXCLUDED.email;

-- Verification
SELECT count(*) as "Total Profiles Now (Should Match Auth Users)" FROM public.profiles;
